### ISSUE TITLE
goro.go:38:8: assignment mismatch: 2 variables but 1 values

### ISSUE THREAD

**Issue by jralph** [vectorhacker/goro#11]
When compiling goro.go is complaining about 2 variables being expected but only 1 returned.

uuid.NewV4() only returns 1 variable, the uuid generated. I believe the code on line 38 should be changed to `id := uuid.NewV4`

**Comment by vectorhacker** [comment]
May I ask how you're vendoring your dependencies? The latest version of github.com/satori/go.uuid returns two arguments when creating uuids whilst some older versions only returns one. The tagged versions is usually what tools like godep like to pin to, instead you should try pinning to a specific commit. I'll try to document this more, but for now the commit I use for the go.uuid project is this: b2ce2384e17bbe0c6d34077efa39dbab3e09123b
