### ISSUE TITLE
Bank Example

### ISSUE THREAD

**Issue by ghost** [vectorhacker/goro#9]
All good CQRS projects need a Bank example to demonstrate usage.

**Comment by vectorhacker** [comment]
hehe, that'd be a neat thing to implement. Though this isn't a CQRS framework, though it can be used to make one. It's just a library for connecting to and using Greg Young's [Event Store](https://eventstore.org/). If you would like to add your own example using this library, I'd be more than happy to see the pull request. I'm working on an examples folder of usages. Again keep in mind this isn't a CQRS framework, but just a client library for the Event Store database.
